### ISSUE TITLE
Refactor geode::web classes, make them pimpl

### ISSUE THREAD

**Issue by matcool** [geode-sdk/geode#388]
# TODO
- [x] Make them pimpl
- [x] Add a method to set request timeout
- [ ] Add a method to abort request completely, without calling any other callbacks
- [ ] POST requests might be broken on curl on windows?
