### ISSUE TITLE
Checklist for 2.206/breaking changes

### ISSUE THREAD

**Issue by matcool** [geode-sdk/geode#792]
- [x] Remove ghc::filesystem (#713)
- [x] Remove sync web request utils
- [x] Remove old web utils, switch to web2
- [x] Merge new index branch? (#712)
- [x] queueInMainThread should take in a move only function
- [x] Remove gd shorthand (#471)
- [x] Remove old fields syntax (#715)
- [x] merge win-64 branch, if the game is even 64 bit
- [x] Remove todoreturn (#714)
- [x] M1 macos support
- [x] Mod updating for the new index
- [x] Remove unused string/wstring utilities
- [x] Update CLI to use new index for mod dependencies
- [x] Add /v1/developers to index
- [x] ~~Tasks mappers should be allowed to return void~~ Task::listen
- [x] things using is_json silently fail if not implemented
- [x] rename windows platform to Win64, remember to update codegen
- [x] ~~fix? android64 exceptions by using c++_shared stl~~ postponed
- [x] use tasks in older apis (file picker)
- [x] implement new file picker api on other platforms

## not abi breaks:
- [ ] fix android gd version check for mods
- [ ] Finish CLI index utils
- [x] Tackling windows compile times
- [x] Fix xmm0 on delayload

**Comment by CaptainJokes** [comment]
Is there a nightly where i can download it?

**Comment by TheSillyDoggo** [comment]
not the place to ask

**Comment by heavyutils** [comment]
Does pre-release work?

**Comment by Idkwhattoputformyusername** [comment]
let's go good progress

**Comment by UniqueName12345** [comment]
HYPE

**Comment by heavyutils** [comment]
> HYPE

Just remember that mods themselves might need an update too. So don't get too hyped
